function(haechi_target_dependencies target)
  foreach(dep IN LISTS ARGN)
    if(TARGET ${dep}::${dep})
      target_link_libraries(${target} ${dep}::${dep})
      get_target_property(_dep_include_dirs ${dep}::${dep} INTERFACE_INCLUDE_DIRECTORIES)
      if(_dep_include_dirs)
        target_include_directories(${target} PUBLIC ${_dep_include_dirs})
      endif()
    elseif(TARGET ${dep})
      target_link_libraries(${target} ${dep})
      get_target_property(_dep_include_dirs ${dep} INTERFACE_INCLUDE_DIRECTORIES)
      if(_dep_include_dirs)
        target_include_directories(${target} PUBLIC ${_dep_include_dirs})
      endif()
    endif()

    if(DEFINED ${dep}_INCLUDE_DIRS)
      target_include_directories(${target} PUBLIC ${${dep}_INCLUDE_DIRS})
    endif()
    if(DEFINED ${dep}_LIBRARIES)
      target_link_libraries(${target} ${${dep}_LIBRARIES})
    endif()
    if(DEFINED ${dep}_DEFINITIONS)
      target_compile_definitions(${target} PUBLIC ${${dep}_DEFINITIONS})
    endif()
  endforeach()
endfunction()
